/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#c5a059',
        'primary-dark': '#b08d4b',
        'background-light': '#fafaf9',
        'background-dark': '#1c1917',
        'stone-dark': '#292524',
        'dried-green': '#7c8057',
        olive: {
          DEFAULT: '#556B2F',
          light: '#768d4d',
          dark: '#3b4d1e',
        },
        gold: {
          DEFAULT: '#C5A059',
          dim: '#a38346',
        },
        paper: '#fdfbf7',
        'primary-green': '#93d411',
        'olive-dark': '#3f4a2c',
        'olive-light': '#7c8961',
        'amethyst-light': '#f4effa',
        'amethyst-border': '#e0d6e8',
        'amethyst-text': '#5e4b75',
        'product-bg-light': '#f7f8f6',
        'product-bg-dark': '#1c2210',
        'admin-primary': '#a4d411',
        'admin-primary-dark': '#8cb60e',
        'admin-olive': '#4a5d23',
        'text-main': '#161811',
        'text-secondary': '#5c6645',
        'accent-stone': '#57534e',
        'soft-stone': '#e7e5e4',
        'text-main-light': '#161811',
        'text-main-dark': '#f3f4f0',
        'text-secondary-light': '#7c8961',
        'text-secondary-dark': '#aab396',
        'surface-light': '#f3f4f0',
        'surface-dark': '#2c3320',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        serif: ['Playfair Display', 'serif', 'ui-serif', 'Georgia'],
        sans: ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        newsreader: ['Newsreader', 'serif'],
        'noto-sans': ['Noto Sans', 'sans-serif'],
        'noto-serif': ['Noto Serif', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      backgroundImage: {
        'paper-texture': "url('https://www.transparenttextures.com/patterns/cream-paper.png')",
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
